-- Active: 1741138916750@@127.0.0.1@3306@base_negocio_landing
USE base_negocio_landing;

-- If you can't load the data using local data local infile
SET GLOBAL local_infile=1;

LOAD DATA LOCAL INFILE 'ftp/csv/CanalDeVenta.csv'  
INTO TABLE canal_venta
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ftp/csv/Cargo.csv' 
INTO TABLE cargo
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/ftp/csv/Clientes.csv'
INTO TABLE cliente
CHARACTER SET utf8
FIELDS TERMINATED BY ';' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE  'ftp/csv/Compra.csv' 
INTO TABLE compra 
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ftp/csv/Empleados.csv'
INTO TABLE empleado
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ftp/csv/Gasto.csv'
INTO TABLE gasto 
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

sLOAD DATA LOCAL INFILE 'ftp/csv/Productos.csv' 
INTO TABLE producto 
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ftp/csv/Proveedores.csv' 
INTO TABLE proveedor
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ftp/csv/Sector.csv' 
INTO TABLE sector
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ftp/csv/Sucursales.csv' 
INTO TABLE sucursal
CHARACTER SET utf8
FIELDS TERMINATED BY ';' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ftp/csv/TiposDeGasto.csv' 
INTO TABLE tipo_gasto
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE  'ftp/csv/Venta.csv' 
INTO TABLE venta
CHARACTER SET utf8
FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"'
LINES TERMINATED BY '\n' IGNORE 1 LINES;